### ISSUE TITLE
IOException when compiling file

### ISSUE THREAD

**Issue by AlexDochioiu** [permissions-dispatcher/kompile-testing#8]
Tried running:
```
@Test
    fun firstTest() {

        //val inFiles = dirToObjectFiles("com.github.alexdochioiu.test1")

        kotlinc()
            .withProcessors(TimeTurnerProcessor())
            .addKotlin(
                "input.kt", """
        package com.github.alexdochioiu.example

        import android.arch.lifecycle.Lifecycle
        import com.github.alexdochioiu.timeturner.GlobalSurvivor
        import com.github.alexdochioiu.timeturner.Survivor
        import com.github.alexdochioiu.timeturner.SurvivorBinding
        import java.util.*

        /**
         * Created by Alexandru Iustin Dochioiu on 30-Jan-19
         */
        @Survivor
        class TestPresenter(lifecycle: Lifecycle) {

            @GlobalSurvivor
            var survivingElements: MutableList<String> = ArrayList()

            @GlobalSurvivor
            var myInt: Int = 2

            @GlobalSurvivor
            var myBool: Boolean = true

            @GlobalSurvivor
            var myStr = "Test"

            init {
            }
        }
        """.trimIndent()
            )
            .compile()
            .succeeded()

    }
```

```
java.io.IOException: Directory 'C:\Users\JeeFo\AppData\Local\Temp\tmp9008736054030136230.tmp\unzippedAar\C:\Users\JeeFo\.gradle\caches\modules-2\files-2.1\com.android.support\appcompat-v7\28.0.0\132586ec59604a86703796851a063a0ac61f697b' could not be created

	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:361)
	at org.apache.commons.io.FileUtils.openOutputStream(FileUtils.java:324)
	at org.apache.commons.io.FileUtils.copyToFile(FileUtils.java:1529)
	at org.apache.commons.io.FileUtils.copyInputStreamToFile(FileUtils.java:1506)
	at kompile.testing.Compiler.extractJarFromAar(Compiler.kt:143)
	at kompile.testing.Compiler.access$extractJarFromAar(Compiler.kt:22)
	at kompile.testing.Compiler$classpathFiles$2.invoke(Compiler.kt:130)
	at kompile.testing.Compiler$classpathFiles$2.invoke(Compiler.kt:22)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at kompile.testing.Compiler.getClasspathFiles(Compiler.kt)
	at kompile.testing.Compiler.fullClasspath(Compiler.kt:95)
	at kompile.testing.Compiler.compile(Compiler.kt:58)
	at com.github.alexdochioiu.timeturnerprocessor.TimeTurnerProcessorTest.firstTest(TimeTurnerProcessorTest.kt:70)
```

P.S. I am running Android Studio 3.3.1 on Windows 10

**Comment by hotchemi** [comment]
Ooh windows...thank you for your report.

**Comment by hotchemi** [comment]
I wonder Apache Commons has some issues.. 🤔

**Comment by AlexDochioiu** [comment]
No need to thank me. I might try to look into this issue myself and start contributing to your project (if you’re happy with that).

P.S. I am pretty interested in what you’re doing

**Comment by mannodermaus** [comment]
The problem seems to be how the extracted JAR is stored on the file system ([here](https://github.com/permissions-dispatcher/kompile-testing/blob/master/src/main/java/kompile/testing/Compiler.kt#L141)):

```kotlin
val newFileName = url.path.replace(".aar", ".jar")
val jar = File(File(rootDir, "unzippedAar"), newFileName)
```

Do we need the entire `url.path` here? On Windows, that'll include the drive name again (`C:` in this case), and that'll become an invalid path. On Mac, a similar path would look like this:

```
/var/folders/df/fz79q8891mn3cfhnsj4bq8rw0000gp/T/tmp3185439907253523255.tmp/unzippedAar/Users/marcel/.gradle/caches/modules-2/files-2.1/androidx.fragment/fragment/1.0.0/b40f6a2ae814f72d1e71a5df6dc1283c00cd52f/fragment-1.0.0.jar
```

Repeating the entire path works on Unix, but not so much Windows. I believe that using only the file name instead of the full path should do the trick:

```kotlin
val newFileName = url.path
            .substringAfterLast(File.separatorChar)
            .replace(".aar", ".jar")
```

**Comment by mannodermaus** [comment]
I raised this as #9 - @AlexDochioiu, if you could test out that branch against your local environment somehow for verification, that would be great!
